### ISSUE TITLE
support connection alias

### ISSUE THREAD

**Issue by lifesign** [TaKO8Ki/gobang#105]
if we have multiple connections, it will be better to support connection alias to distinguish

**Comment by TaKO8Ki** [comment]
So you mean you want to name each connection?

**Comment by lifesign** [comment]
Yes, if we have multiple connection configurations, it can be difficult to tell which connections are production environment and which are test environment

**Comment by TaKO8Ki** [comment]
Ok. I understand. I'm going to implement this feature :)
