### ISSUE TITLE
Password support?

### ISSUE THREAD

**Issue by passcod** [TaKO8Ki/gobang#73]
Am I missing something? How do I give a password for mysql?

**Comment by TaKO8Ki** [comment]
Oh, I totally forgot! I'm going to fix gobang as soon as possible.

**Comment by TaKO8Ki** [comment]
I've just fixed it. I'm going to release it later :)

https://github.com/TaKO8Ki/gobang/pull/74

**Comment by TaKO8Ki** [comment]
@passcod I'm releasing v0.1.0-alpha.3 now! 👍

**Comment by TaKO8Ki** [comment]
I just finished releasing v0.1.0-alpha.3!
